---
title: "C28163 | Microsoft Docs"
ms.custom: ""
ms.date: "12/05/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C28163"
helpviewer_keywords: 
  - "C28163"
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
caps.latest.revision: 3
caps.handback.revision: 3
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
---
# C28163
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

warning C28163: La funzione non deve essere mai chiamata dall'interno di un blocco try\/except.  
  
 Questo avviso viene visualizzato quando una funzione Ã¨ di un tipo che non venga mai incluso in un blocco di `try/except` viene trovato in un blocco di `try/except`.  Lo strumento di analisi del codice ha rilevato almeno un percorso in cui la funzione chiamata era all'interno di un blocco `try/except`.