---
title: "C6103 | Microsoft Docs"
ms.custom: ""
ms.date: "12/05/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C6103"
ms.assetid: 22d1ab35-31a3-4ba9-8ef4-7a64bce66621
caps.latest.revision: 4
caps.handback.revision: 4
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
---
# C6103
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

Avviso C6103: restituzione di \<variabile\> dalla chiamata di funzione non riuscita alla riga \<percorso\>.  
  
 Un percorso corretto tramite la funzione restituisce una variabile utilizzata come parametro `_Out_` a una chiamata di funzione interna non riuscita.  
  
 Il problema potrebbe essere causato dal fatto che la funzione chiamata e la funzione chiamante non sono completamente annotate.  La funzione chiamata può richiedere `_Always_`, `_Outptr_result_nullonfailure_` \(`_COM_Outptr_` per codice COM\) o un'annotazione correlata e la funzione chiamante può richiedere un'annotazione `_Success_`.  Un'altra causa possibile del problema consiste nel fatto che l'annotazione `_Success_` nella funzione chiamata non è corretta.  
  
## Vedere anche  
 [Uso delle annotazioni SAL per ridurre gli errori del codice C\/C\+\+](../code-quality/using-sal-annotations-to-reduce-c-cpp-code-defects.md)