---
title: "C6310 | Microsoft Docs"
ms.custom: ""
ms.date: "11/04/2016"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C6310"
helpviewer_keywords: 
  - "C6310"
ms.assetid: e759eb63-883f-4c3e-bf2f-b924ff511405
caps.latest.revision: 13
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
caps.handback.revision: 13
---
# C6310
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

avviso C6310: una costante non valida nel filtro eccezioni può provocare comportamenti imprevisti  
  
 Il messaggio indica che è stata rilevata una costante non valida nell'espressione di filtro di un gestore delle eccezioni strutturato.  Le costanti definite per l'utilizzo nell'espressione di filtro di un gestore delle eccezioni strutturato sono:  
  
-   `EXCEPTION_CONTINUE_EXECUTION`  
  
-   `EXCEPTION_CONTINUE_SEARCH`  
  
-   `EXCEPTION_EXECUTE_HANDLER`  
  
 Questi valori sono definiti nel file di intestazione runtime excpt.h.  
  
 L'utilizzo di una costante non inclusa nell'elenco precedente può determinare un comportamento imprevisto.  
  
## Esempio  
 Il codice seguente genera questo avviso:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
BOOL LimitExceeded();  
  
void fd( )  
{  
  __try   
  {  
    if (LimitExceeded())   
    {  
      RaiseException(EXCEPTION_ACCESS_VIOLATION,0,0,0);  
    }  
    else  
    {  
      // code   
    }  
  }   
  __except (EXCEPTION_ACCESS_VIOLATION)  
  {  
    puts("Exception Occurred");  
  }  
}  
```  
  
 Per risolvere il problema, utilizzare il codice seguente:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
BOOL LimitExceeded();  
  
void fd( )  
{  
  __try   
  {  
    if (LimitExceeded())   
    {  
      RaiseException(EXCEPTION_ACCESS_VIOLATION,0,0,0);  
    }  
    else  
    {  
      // code   
    }  
  }   
  __except (GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
  {  
    puts("Exception Occurred");  
  }  
}  
```